"use client";

import { ShieldAlert, UserCog } from "lucide-react";
import { useApp } from "@/src/store/app-context";
import type { DemoRole } from "@/src/config/permissions";

export function DemoControls() {
  const { role, setRole } = useApp();
  return <main className="page"><div className="page-head"><div><div className="eyebrow">Prototype access</div><h1>Prototype Controls</h1><p className="page-subtitle">Demonstrate permission-aware UX without fake production authentication</p></div></div><div className="callout warning"><strong>Prototype Authentication:</strong> Role switching controls the visible UI only. A production backend must authenticate and authorize every request.</div><section className="card setting-card" style={{ marginTop: 13 }}><div className="card-head" style={{ padding: 0 }}><div><h2>Demo role</h2><p>Switch the visible permission experience</p></div><UserCog /></div>{(["ADMIN", "BUSINESS_DEVELOPMENT", "ANALYST", "PARTNER", "VIEWER"] as DemoRole[]).map(value => <div className="setting-row" key={value}><div><strong>{value.replaceAll("_", " ")}</strong><span>{value === "ADMIN" ? "All prototype controls" : value === "BUSINESS_DEVELOPMENT" ? "Opportunities, analysis and partners" : value === "ANALYST" ? "Analysis and view access" : value === "PARTNER" ? "Submit and view own prototype submissions" : "Read-only"}</span></div><button className={`toggle ${role === value ? "on" : ""}`} aria-label={`Use ${value} demo role`} aria-pressed={role === value} onClick={() => setRole(value)} /></div>)}</section><section className="card section-card" style={{ marginTop: 13 }}><h2>Current data path</h2><div className="architecture-flow"><span className="architecture-node">UI Features</span><span className="architecture-arrow">→</span><span className="architecture-node">Provider / API adapters</span><span className="architecture-arrow">→</span><span className="architecture-node">Public APIs or Business REST API</span></div><div className="callout warning" style={{ marginTop: 13 }}><ShieldAlert />API failure and empty states are shown from actual connection outcomes; the application no longer injects a mock market dataset.</div></section></main>;
}
