"use client";

import { ShieldAlert, UserCog } from "lucide-react";
import { useApp } from "@/src/store/app-context";
import type { DemoRole } from "@/src/config/permissions";

// สลับ `role` ใน AppProvider ซึ่งควบคุมแค่ UI ฝั่ง client (ดู hasPermission ใน app-context.tsx)
// ไม่ได้เชื่อมกับ backend จริง จึงจำลองความล้มเหลวของการยืนยันตัวตนจริงไม่ได้
export function DemoControls() {
  const { role, setRole, language } = useApp();
  const th = language === "th";
  return <main className="page"><div className="page-head"><div><div className="eyebrow">{th ? "สิทธิ์การใช้งานต้นแบบ" : "Prototype access"}</div><h1>{th ? "การควบคุมต้นแบบ" : "Prototype Controls"}</h1><p className="page-subtitle">{th ? "สาธิต UX ตามสิทธิ์โดยไม่อ้างว่าเป็นการยืนยันตัวตนสำหรับระบบจริง" : "Demonstrate permission-aware UX without fake production authentication"}</p></div></div><div className="callout warning"><strong>{th ? "การยืนยันตัวตนต้นแบบ:" : "Prototype Authentication:"}</strong> {th ? "การสลับบทบาทมีผลเฉพาะ UI ระบบจริงต้องยืนยันตัวตนและสิทธิ์ทุกคำขอที่ระบบหลังบ้าน" : "Role switching controls the visible UI only. A production backend must authenticate and authorize every request."}</div><section className="card setting-card" style={{ marginTop: 13 }}><div className="card-head" style={{ padding: 0 }}><div><h2>{th ? "บทบาทสาธิต" : "Demo role"}</h2><p>{th ? "สลับประสบการณ์ตามสิทธิ์ที่มองเห็น" : "Switch the visible permission experience"}</p></div><UserCog /></div>{(["ADMIN", "BUSINESS_DEVELOPMENT", "ANALYST", "PARTNER", "VIEWER"] as DemoRole[]).map(value => <div className="setting-row" key={value}><div><strong>{value.replaceAll("_", " ")}</strong><span>{value === "ADMIN" ? (th ? "ใช้ตัวควบคุมต้นแบบทั้งหมด" : "All prototype controls") : value === "BUSINESS_DEVELOPMENT" ? (th ? "โอกาส การวิเคราะห์ และพันธมิตร" : "Opportunities, analysis and partners") : value === "ANALYST" ? (th ? "วิเคราะห์และดูข้อมูล" : "Analysis and view access") : value === "PARTNER" ? (th ? "ส่งและดูรายการต้นแบบของตน" : "Submit and view own prototype submissions") : (th ? "อ่านอย่างเดียว" : "Read-only")}</span></div><button className={`toggle ${role === value ? "on" : ""}`} aria-label={`${th ? "ใช้บทบาทสาธิต" : "Use"} ${value}`} aria-pressed={role === value} onClick={() => setRole(value)} /></div>)}</section><section className="card section-card" style={{ marginTop: 13 }}><h2>{th ? "เส้นทางข้อมูลปัจจุบัน" : "Current data path"}</h2><div className="architecture-flow"><span className="architecture-node">UI Features</span><span className="architecture-arrow">→</span><span className="architecture-node">Provider / API adapters</span><span className="architecture-arrow">→</span><span className="architecture-node">Public APIs or Business REST API</span></div><div className="callout warning" style={{ marginTop: 13 }}><ShieldAlert />{th ? "สถานะ API ล้มเหลวและไม่มีข้อมูลมาจากผลการเชื่อมต่อจริง ระบบไม่แทรกชุดข้อมูลตลาดจำลองอีกต่อไป" : "API failure and empty states are shown from actual connection outcomes; the application no longer injects a mock market dataset."}</div></section></main>;
}
